### ISSUE TITLE
Finding eigenvectors

### ISSUE THREAD

**Issue by axyuan** [lvandeve/jmat#11]
Hello,

Thanks for all your work on this library - it's amazing.

I'm having trouble getting eigenvectors out for certain matrices, e.g.:

[ 1, 9, 9, 0.11, 9 ]
[ 0.11, 1, 0.11, 1, 1 ]
[ 0.11, 9, 1, 5, 1 ]
[ 9, 1, 0.2, 1, 1 ]
[ 0.11, 1, 1, 1, 1 ]

Do you know what could be wrong?

Thanks a lot.

**Comment by lvandeve** [comment]
Hi,

I tried to improve things a little bit, and now it works at least on the above example. Try running in the JS console:
Jmat.render(Matrix.eig(Matrix([[1,9,9,0.11,9],[0.11,1,0.11,1,1],[0.11,9,1,5,1],[9,1,0.2,1,1],[0.11,1,1,1,1]])))

For the symmetric flag: probably I'd make it not a flag but make it detect if the matrix is hermitian. Speeding things up given this information requires, of course, a new algorithm which is currently not yet there, so this is not done yet.

The eigenvalues are calculated with a double shifting version of the QR algorithm. However the implementation still needs quite a bit of improvements for both speed and accuracy (or could use an alternative algorithm). So the eigenvalues are unfortunately not always super precise and there may still be bugs...

The eigenvectors are solved with the characteristic equation with SVD, and the SVD now has a really stable implementation based on Linpack so I think this should work well, but of course is affected by the precision of the eigenvalues from above. This is not the fastest possible algorithm though.

If you have any ideas for improving the QR algorithm implementation, or better algorithms to use for eigenvalues and/or eigenvectors, that would be very welcome :)

After the latest commit, if you find any more problem examples, it would be very interesting to know them to try to improve on that.

**Comment by axyuan** [comment]
Thank you so much for looking into this. Indeed it works perfectly now. 

Unfortunately I'm useless on the implementation front :) 

I'm interested in finding eigenvectors in order to implement the analytic hierarchy process (https://en.wikipedia.org/wiki/Analytic_hierarchy_process_%E2%80%93_leader_example). I have a test running on oughtness.cc which uses 5 alternatives (for a 5x5 matrix - the results of which are in the "data" tab), but I'd love to eventually get up to maybe a few dozen alternatives processed in real time. 

Is that insane? Any possibility you'd be willing to implement a less precise but faster version for larger matrices?

Thanks again.
