### ISSUE TITLE
qf_normal gives unexpected results

### ISSUE THREAD

**Issue by astrozot** [lvandeve/jmat#12]
I am not sure I understand exactly what the qf_xxx functions do, but I believe they are the inverse of the cdf_xxx functions.  In this case, I think the qf_normal gives wrong results, because, for example

qf_normal(0, 0, 1) = 0

instead of -Infinity, and 

qf_normal(0.5, 0, 1) = 1

instead of 0.  The error, presumably, is the exponential function used inside the definition of qf_normal: 

Jmat.Complex.qf_normal = function(x, mu, sigma) {
    return Jmat.Complex.exp(mu.add(sigma.mul(Jmat.Complex.qf_standardnormal(x))));
};

should probably be just

Jmat.Complex.qf_normal = function(x, mu, sigma) {
    return mu.add(sigma.mul(Jmat.Complex.qf_standardnormal(x)));
};

**Comment by lvandeve** [comment]
Thanks for finding this bug, you're absolutely correct, no idea how the exp ended up there, sorry for that inconvenience :/
