### ISSUE TITLE
Dropped NaN in polylog function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#14]
Evaluating `polylog(NaN, 2.2738632088209076)` gives the result `1.136931604`

Perhaps propagating the NaN is preferable; this is the behavior that occures when making the second argument NaN

**Comment by lvandeve** [comment]
I couldn't reproduce this one (gave NaN for the example input above), but I added NaN checks at the start of the function now so it should work correctly in any case now.

Done in commit https://github.com/lvandeve/jmat/commit/2ce5dace0737d96493945b81ee556d2b899d9290

Feel free to reopen if necessary. Thanks for reporting this!
