### ISSUE TITLE
Dropped NaN in airy and airy_deriv functions

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#16]
Evaluating any of `airy(NaN)`, `bairy(NaN)`, `airy_deriv(NaN)`, or `bairy_deriv` results in `0`. Perhaps propagating the NaN is a safer approach.

**Comment by lvandeve** [comment]
Done in commit https://github.com/lvandeve/jmat/commit/2ce5dace0737d96493945b81ee556d2b899d9290

Feel free to reopen if necessary. Thanks for reporting this!
