### ISSUE TITLE
Unexpected result from polylog function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#19]
When the first argument passed to the polylog function is an infinity, the function returns a double, ie `polylog(inf, 2.27386)` returns `1.136931`. Such a computation is erroneous and is recognized as such by mpmath's implementation of the same function which returns a NaN in the above case.

**Comment by lvandeve** [comment]
For me Jmat.polylog(Infinity, 2.27386) returns 2.27386 instead of 1.136931. Are you using the latest version?

It does appear to be the correct limit (going towards the second argument if the first argument goes towards infinity), but let me know if that's mathematically incorrect

**Comment by jacksonvanover** [comment]
My apologies! Looks like there was a bug in our testing framework that led to the erroneous result that's now been fixed.

As for the limit, that intuitively seems correct to me; thanks for being so responsive
