### ISSUE TITLE
Unexpected Result from besselj

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#20]
Evaluating the besselj function with either of the arguments as an infinity gives a zero but the implementations in GSL, SciPy, and mpmath all return NaNs or throw exceptions.

**Comment by lvandeve** [comment]
Wolfram Alpha and octave output 0 for some infinities in this case, but not for others (depending on sign and complex), so I refined the checks for this one, but it'll still return 0 for positive infinity of either nu or z.

**Comment by lvandeve** [comment]
Done in commit https://github.com/lvandeve/jmat/commit/2ce5dace0737d96493945b81ee556d2b899d9290

Feel free to reopen if necessary. Thanks!
