### ISSUE TITLE
limit of eta function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#21]
Elsewhere in the JMAT library, limits approaching infinity are handled, e.g. evaluating `erf(inf)` returns a `1` as expected. However, when evaluating `eta(inf)`, we get a `NaN` as a return even though the limit for the eta function as x approaches infinity is 1.

**Comment by lvandeve** [comment]
Done in commit https://github.com/lvandeve/jmat/commit/2ce5dace0737d96493945b81ee556d2b899d9290

Feel free to reopen if necessary. Thanks for reporting this!
