### ISSUE TITLE
limits of incomplete gamma functions

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#22]
evaluating `jmat_incgamma_upper(x, inf)`, `gamma_q(x, inf)`, and `gamma_p(x,inf)` where x is a floating point number results in a complex return value with infinite real and imaginary parts when the actual limits should be 0, 0, and 1 respectively.

**Comment by lvandeve** [comment]
Thanks for the analysis! Fixed in https://github.com/lvandeve/jmat/commit/b0d7363383021a889b47c037e3dd2ad30aaedae4
