### ISSUE TITLE
Unexpected Result from binomial with inf input

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#23]
When the first argument to `binomial` is infinity and the second input is positive, a mysterious numerical result is returned, e.g. `binomial(inf, 2.27)` results in `0.38434544335574816`. As the second argument increases, it appears that the limit approaches zero. Wouldn't it make sense to consistently return Inf in this case? Or perhaps a NaN or exception and disallow an Inf for a first parameter...

**Comment by lvandeve** [comment]
Thanks! Handled several cases of infinity correct and returning NaN for others, in commit https://github.com/lvandeve/jmat/commit/b0d7363383021a889b47c037e3dd2ad30aaedae4
