### ISSUE TITLE
Unexpected Result from beta with inf input

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#24]
So I'm not exactly sure what the expected result is but...

When evaluating `beta(x, inf)` where x is some positive numerical input, mpmath and scipy return `0` and gsl returns a `NaN` (perhaps an indication that their implementation doesn't support limits?). On the other hand, JMAT is returning a numerical result which seems incorrect by comparison.

**Comment by lvandeve** [comment]
Thanks for the analysis! I made it return 0 for positive infinty y and NaN for various other cases in commit https://github.com/lvandeve/jmat/commit/b0d7363383021a889b47c037e3dd2ad30aaedae4
