### ISSUE TITLE
Unpredictable Results from eta function for negative inputs

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#26]
jmat does not always agree with mpmath, gsl, and other resources when the `eta` function is given negative arguments:

When evaluating `eta(-45)`:
 - mpmath/gsl give `3.2355470001722734e+33`
 - jmat gives `3.235547000172278e+33`

When evaluating `eta(-50)`:
 - mpmath/gsl give `0`
 - jmat gives `-1.3201654410192226e+24`

When evaluating `eta(-55)`:
 - mpmath/gsl give `-3.6670584803153007e+45`
 - jmat gives `-3.6670584803153064e+45`

When evaluating `eta(-56)`:
 - mpmath/gsl give `0`
 - jmat gives `-2.2414284151428972e+32`

**Comment by lvandeve** [comment]
Thanks for reporting! Should be fixed in commit https://github.com/lvandeve/jmat/commit/0baf836907bcbedbaa8fb0d3fe5297411452ba31
