### ISSUE TITLE
Unexpected NaN returned from gamma_p_inv function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#31]
When the second argument to the `gamma_p_inv` function is a zero, the
expected return is also zero, provided that the first argument is
positive (I don't believe the normalized incomplete gamma functions
are defined for non-positive first parameters). This is indeed what I
observe when the first argument is a positive integer. However, when
that first argument is non-integral, the return is a NaN, e.g.

`Jmat.gamma_p_inv(3,0)` evaluates to 0
`Jmat.gamma_p_inv(3.1,0)` evaluates to NaN

**Comment by lvandeve** [comment]
Thanks for reporting, fixed with commit https://github.com/lvandeve/jmat/commit/979131b27a09edea0391cff0fa3f239b80736867

I'm aware of the other bug reports too, this one was easy to fix :)

**Comment by jacksonvanover** [comment]
No worries! Thanks again for being so responsive! This really is such an impressive piece of software that you’ve built
