### ISSUE TITLE
Unexpected return from gamma_q function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#33]
When the magnitude of the second argument to the `Jmat.gamma_q`
function is large enough, the return value becomes complex while it
appears that the correct asymptotic behavior is to approach zero.

ex:

`Jmat.gamma_q(1,15)` returns `3.058805404521081e-7`
`Jmat.gamma_q(1,16)` returns
`1.1253517473441832e-7+1.2246467991473532e-16i`

`Jmat.gamma_q(10, 87)` returns `1.84297022087776e-14`
`Jmat.gamma_q(10, 88)` returns `7.193232413504669e-43i`

**Comment by lvandeve** [comment]
Should be fixed by commit ff8a84912c8108f2a8fad7ba2f214895825da9dc

Thanks for reporting this!
