### ISSUE TITLE
unexpected return from permutation function

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#35]
When the first argument is infinite, the `Jmat.permutation` consistently returns 1 regardless of the second argument; a NaN seems more appropriate.

**Comment by lvandeve** [comment]
It returns NaN in the current head version, this should have been fixed by the commit https://github.com/lvandeve/jmat/commit/b0d7363383021a889b47c037e3dd2ad30aaedae4, maybe it's broken in an older version
