### ISSUE TITLE
Small imaginary components with otherwise correct real parts

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#36]
`Jmat.beta(-68.1, -79.8)` returns `-7.356207346516703e+43re-7.930437097026547e+29i`
`Jmat.beta(-68.2, -79.8)` returns `-0.0`
`Jmat.beta(-68.2, -79.87)` returns `4.4678160475081424e+42`
`Jmat.beta(-68.2, -79.7)` returns `-2.854033257329725e+43re-3.0768207248525484e+29i`

The real parts of these returns are all on the order of the results from SciPy, mpmath, and GSL, but the introduction of the imaginary components seems spurious. I'm observing similar behavior for the evaluation of `besseli(1, 12)` and `besselk(12,12)` as well as in the issues below

https://github.com/lvandeve/jmat/issues/33
https://github.com/lvandeve/jmat/issues/29

**Comment by jacksonvanover** [comment]
Also observed with `hypergeometric1F1(-10, 1, 80)`, `hypergeometric1F1(1, 2, -17)`

**Comment by lvandeve** [comment]
Should be fixed for beta function with commit https://github.com/lvandeve/jmat/commit/09486d772ad3de8abac95a142764529c75c71fc4

hypergeometric still todo

**Comment by lvandeve** [comment]
hypergeometric1F1 should be fixed with commit https://github.com/lvandeve/jmat/commit/1f6919ed981167030219c05c6a1f5835f635c1d5
