### ISSUE TITLE
hypergeometric1F1 returning incorrect results for nonpositive integers

### ISSUE THREAD

**Issue by jacksonvanover** [lvandeve/jmat#37]
When evaluating `hypergeometric1F1` with zero as the second and third arguments, the return is consistently 1 even though the confluent
hypergeometric function does not exist when the second argument is a nonpositive integer
(see https://dlmf.nist.gov/13.2)

**Comment by lvandeve** [comment]
Thanks for pointing out!

Should be fixed in https://github.com/lvandeve/jmat/commit/ec2985dd3b348234915963aabe2d895633b4922a

It looks like it's a bit more subtle since some combinations with nonpositive integer a can give finite results, those are implemented too
