### ISSUE TITLE
Incorrect handling of values that evaluate to false

### ISSUE THREAD

**Issue by pyramids** [lvandeve/jmat#7]
```
Jmat.Matrix.cast([0,3]).toString()
```
incorrectly yields `"[[], []]"` instead of the expected `[[0],[3]]`; any other number works correctly. This causes incorrect behavior of `Jmat.transpose([0,3])` and an exception to be thrown from `Jmat.mul([1,2], Jmat.transpose([0,3]))`. My impression of the internal functions involved is that this is unintended behavior and the support for 1d arrays to represent 1d matrices intended. If so, this is a bug.

The problem is probably the use of constructs like `(a && a[y])` throughout Jmat, here in the `softr` functiions inside `Jmat.Matrix.make`. It is likely that most (and perhaps all) of similar constructs in Jmat unintentionally evaluate to false when given a zero value. The issue I am trying to flag is that these probably need to be replaced with constructs such as `(("undefined" !== typeof a) && ("undefined" !== typeof a[y]))`. Better documentation of intended behavior would help, too.

**Comment by lvandeve** [comment]
Thanks for finding this bug! Yeah didn't take into account JS's evaluation of [0] to false. I think the last commit should have fixed it. It was indeed not intended behaviour like that.

Feel free to reopen if you still find such issues.

**Comment by pyramids** [comment]
I should have watched this...my own fix is getting ready only just now!
