### ISSUE TITLE
Jmat.Matrix.solve does not find inconsistent systems

### ISSUE THREAD

**Issue by astrozot** [lvandeve/jmat#9]
Hi,

I found that Jmat.Matrix.solve does not find inconsistent systems: it calls Jmat.Matrix.near to compare b with the corresponding term obtained from the solution, but calls this function without the epsilon argument.  As a result, epslion === undefined and each solution appears always to be acceptable.

**Comment by lvandeve** [comment]
Thanks for finding the bugs, fixed :)

**Comment by astrozot** [comment]
Perfect, thank you for the fast reaction!

Il giorno gio 25 giu 2015 alle 22:11 lvandeve <notifications@github.com> ha
scritto:

> Thanks for finding the bugs, fixed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lvandeve/jmat/issues/9#issuecomment-115380862>.
>
-- 
Dr. Marco Lombardi
Phone: +39 334 5853843 url: http://www.marcolombardi.org
